apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  labels:
    app: go-sample
spec:
  # とりあえず2つのpodに設定しておく
  replicas: 2
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          # ローカルで作成したイメージを使用
          image: go-api-image
          # ローカルのイメージを使用するため、imagePullPolicyをIfNotPresentに設定
          imagePullPolicy: Never
          # コンテナのポートは8000
          ports:
            - containerPort: 8000