apiVersion: v1
kind: Service
metadata:
  name: go-api
  labels:
    app: go-api
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: go-api
  type: LoadBalancer